name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t snrainiar/docker-skland-daily .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: snrainiar
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docket Hub
        run: docker push snrainiar/docker-skland-daily:latest
